In [1]:
import pandas as pd

In [2]:
info = {
    "Name" : ["Aryan", "Rahul", "Rohan"],
    "CGPA": [9.0, 8.7, 9.5]
}

df = pd.DataFrame(info)
print(df)

    Name  CGPA
0  Aryan   9.0
1  Rahul   8.7
2  Rohan   9.5

In [3]:
df

    Name  CGPA
0  Aryan   9.0
1  Rahul   8.7
2  Rohan   9.5

In [4]:
#series (1D labelled array)

s = pd.Series([1,2,3,4,5])
print(s)
print(type(s))

#indexing
print(s[0])
print(s[3])

0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.Series'>
1
4

In [5]:
s = pd.Series([23,56,45,12,"abc"], index=["Adam", "Eve", "Bob", "Charlie", 25])
print(s)

#index
print(s["Adam"]) #23
# print(s[0])

#print  all index values
print(s.index)

Adam        23
Eve         56
Bob         45
Charlie     12
25         abc
dtype: object
23
Index(['Adam', 'Eve', 'Bob', 'Charlie', 25], dtype='object')

In [6]:
#vectorized operation on series

s1 = pd.Series([1,2,3,4,5])
s2 = pd.Series([10,20,30,40,50])

print(s1+s2)

s1[0] = 100 #MUTABLE VLAUES
print(s1)

#IMMUTABLE SIZE
changed_s1 = s1.drop(0)
print(changed_s1)

0    11
1    22
2    33
3    44
4    55
dtype: int64
0    100
1      2
2      3
3      4
4      5
dtype: int64
1    2
2    3
3    4
4    5
dtype: int64

In [7]:
#dataframe

info = {
    "Name" : ["Adam", "Bob", "Eve"],
    "Age" : [21,23,34],
    "GPA": [6.7,8.0,9.5]
}

df = pd.DataFrame(info)
print(df)
print(type(df))
print(df.index)

   Name  Age  GPA
0  Adam   21  6.7
1   Bob   23  8.0
2   Eve   34  9.5
<class 'pandas.DataFrame'>
RangeIndex(start=0, stop=3, step=1)

In [8]:
df

   Name  Age  GPA
0  Adam   21  6.7
1   Bob   23  8.0
2   Eve   34  9.5

In [9]:
#list of lists 
df = pd.DataFrame([["Adam", 23],["Eve", 23],["Bob", 23]], columns = ["Name", "Age"])
print(df)

   Name  Age
0  Adam   23
1   Eve   23
2   Bob   23

In [10]:
#using NumPy arrays
import numpy as np
np_arr = np.array([[1,2,3], [4,5,6]])

df = pd.DataFrame(np_arr, columns=["A", "B", "C"])
print(df)

   A  B  C
0  1  2  3
1  4  5  6

In [11]:
#csv data load - importing
df_csv = pd.read_csv("employee_data.csv")
print(df_csv)
print(type(df_csv))

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000
<class 'pandas.DataFrame'>

In [12]:
#json data laod - exporting
df_json = pd.read_json("employee_data.json") 
print(df_json)
print(type(df_json))

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000
<class 'pandas.DataFrame'>

In [13]:
df = pd.read_csv("globalAirQuality.csv")

print(df)

                        timestamp country      city  latitude  longitude  \
0      2025-11-04 18:25:17.554219      US  New York    40.713    -74.006
1      2025-11-04 19:25:17.554219      US  New York    40.713    -74.006
2      2025-11-04 20:25:17.554219      US  New York    40.713    -74.006
3      2025-11-04 21:25:17.554219      US  New York    40.713    -74.006
4      2025-11-04 22:25:17.554219      US  New York    40.713    -74.006
...                           ...     ...       ...       ...        ...
17995  2025-11-19 13:25:17.554219      CH    Zurich    47.377      8.542
17996  2025-11-19 14:25:17.554219      CH    Zurich    47.377      8.542
17997  2025-11-19 15:25:17.554219      CH    Zurich    47.377      8.542
17998  2025-11-19 16:25:17.554219      CH    Zurich    47.377      8.542
17999  2025-11-19 17:25:17.554219      CH    Zurich    47.377      8.542

         pm25     pm10     no2    so2      o3     co  aqi  temperature  \
0      50.295  108.938  27.998  6.539  52.568  1.096  108       18.504
1      32.083   63.043  36.120  4.021  43.536  1.075   90        5.838
2      42.250   82.553  26.935  9.538  23.320  0.977   84       31.833
3      30.403   79.951  63.536  7.609  31.369  0.230  158       23.140
4      21.083   66.423  38.997  6.919  45.615  1.085   97       13.632
...       ...      ...     ...    ...     ...    ...  ...          ...
17995  27.899   74.179  41.474  6.677  50.869  1.028  103        7.079
17996   2.950   47.988  42.235  2.821  35.551  0.644  105       28.734
17997  61.347   72.908  46.976  5.763  66.492  0.947  122       21.951
17998  40.722   95.152  32.957  5.524  53.193  0.868   95       24.042
17999  25.830   30.411  35.317  4.336  66.246  0.848   88        8.529

       humidity  wind_speed
0        70.168       3.725
1        80.088       8.969
2        62.783       9.650
3        89.153       8.956
4        76.499       4.017
...         ...         ...
17995    52.443       7.452
17996    85.678       4.496
17997    72.311       9.660
17998    31.880       2.642
17999    59.104       4.403

[18000 rows x 15 columns]

In [14]:
df.head()

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
1,2025-11-04 19:25:17.554219,US,New York,40.713,-74.006,32.083,63.043,36.120,4.021,43.536,1.075,90,5.838,80.088,8.969
2,2025-11-04 20:25:17.554219,US,New York,40.713,-74.006,42.250,82.553,26.935,9.538,23.320,0.977,84,31.833,62.783,9.650
3,2025-11-04 21:25:17.554219,US,New York,40.713,-74.006,30.403,79.951,63.536,7.609,31.369,0.230,158,23.140,89.153,8.956
4,2025-11-04 22:25:17.554219,US,New York,40.713,-74.006,21.083,66.423,38.997,6.919,45.615,1.085,97,13.632,76.499,4.017

In [15]:
df.tail()

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
17995,2025-11-19 13:25:17.554219,CH,Zurich,47.377,8.542,27.899,74.179,41.474,6.677,50.869,1.028,103,7.079,52.443,7.452
17996,2025-11-19 14:25:17.554219,CH,Zurich,47.377,8.542,2.950,47.988,42.235,2.821,35.551,0.644,105,28.734,85.678,4.496
17997,2025-11-19 15:25:17.554219,CH,Zurich,47.377,8.542,61.347,72.908,46.976,5.763,66.492,0.947,122,21.951,72.311,9.660
17998,2025-11-19 16:25:17.554219,CH,Zurich,47.377,8.542,40.722,95.152,32.957,5.524,53.193,0.868,95,24.042,31.880,2.642
17999,2025-11-19 17:25:17.554219,CH,Zurich,47.377,8.542,25.830,30.411,35.317,4.336,66.246,0.848,88,8.529,59.104,4.403

In [16]:
df.describe()

,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
count,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000
mean,23.065980,37.655560,40.369131,70.152228,32.055176,6.035508,48.065100,0.800595,104.645556,21.510251,57.714351,5.283910
std,26.156536,78.600701,17.647450,24.999440,13.820680,2.454790,14.950849,0.250254,25.616070,9.509444,18.844908,2.741712
min,-37.814000,-123.121000,0.025000,0.061000,0.013000,0.003000,0.114000,0.000000,16.000000,5.000000,25.002000,0.500000
25%,12.972000,2.352000,27.904500,53.125500,22.362500,4.360750,38.028500,0.633000,87.000000,13.357750,41.320000,2.937000
50%,29.232000,42.146000,40.286500,69.961000,32.019500,6.026000,48.142000,0.800500,103.000000,21.455500,57.847000,5.297000
75%,41.008000,103.820000,52.436250,87.256500,41.364250,7.715250,58.258500,0.969000,121.000000,29.688250,74.234750,7.662000
max,60.170000,174.763000,115.683000,161.810000,90.019000,16.559000,103.016000,1.832000,231.000000,37.998000,89.997000,9.999000

In [17]:
#selecting data

df["country"]

0        US
1        US
2        US
3        US
4        US
         ..
17995    CH
17996    CH
17997    CH
17998    CH
17999    CH
Name: country, Length: 18000, dtype: str

In [18]:
#selecting data from columns
# df["city"]
df[["city","aqi"]]

           city  aqi
0      New York  108
1      New York   90
2      New York   84
3      New York  158
4      New York   97
...         ...  ...
17995    Zurich  103
17996    Zurich  105
17997    Zurich  122
17998    Zurich   95
17999    Zurich   88

[18000 rows x 2 columns]

In [19]:
df

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
1,2025-11-04 19:25:17.554219,US,New York,40.713,-74.006,32.083,63.043,36.120,4.021,43.536,1.075,90,5.838,80.088,8.969
2,2025-11-04 20:25:17.554219,US,New York,40.713,-74.006,42.250,82.553,26.935,9.538,23.320,0.977,84,31.833,62.783,9.650
3,2025-11-04 21:25:17.554219,US,New York,40.713,-74.006,30.403,79.951,63.536,7.609,31.369,0.230,158,23.140,89.153,8.956
4,2025-11-04 22:25:17.554219,US,New York,40.713,-74.006,21.083,66.423,38.997,6.919,45.615,1.085,97,13.632,76.499,4.017
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17995,2025-11-19 13:25:17.554219,CH,Zurich,47.377,8.542,27.899,74.179,41.474,6.677,50.869,1.028,103,7.079,52.443,7.452
17996,2025-11-19 14:25:17.554219,CH,Zurich,47.377,8.542,2.950,47.988,42.235,2.821,35.551,0.644,105,28.734,85.678,4.496
17997,2025-11-19 15:25:17.554219,CH,Zurich,47.377,8.542,61.347,72.908,46.976,5.763,66.492,0.947,122,21.951,72.311,9.660
17998,2025-11-19 16:25:17.554219,CH,Zurich,47.377,8.542,40.722,95.152,32.957,5.524,53.193,0.868,95,24.042,31.880,2.642
17999,2025-11-19 17:25:17.554219,CH,Zurich,47.377,8.542,25.830,30.411,35.317,4.336,66.246,0.848,88,8.529,59.104,4.403

In [23]:
#selecting rows
df.loc[0] #first row data
df.loc[0:2] #row slicing : start index : ending index (inclusive)
df.iloc[2]
df.iloc[0:2] #start index : ending index (exclusive)

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
1,2025-11-04 19:25:17.554219,US,New York,40.713,-74.006,32.083,63.043,36.120,4.021,43.536,1.075,90,5.838,80.088,8.969

In [27]:
#selecting individual cells - row & col
df.loc[0, "aqi"]
df.loc[0:2, ["city", "aqi"]]
df.iloc[0:2, 2]

0    New York
1    New York
Name: city, dtype: str

In [33]:
#selecting single scaler value 
df.at[0, "city"]
df.iat[0, 2]

'New York'

In [37]:
cities = df["city"].copy() #copy
cities[0] = "Mumbai" #copy  | no change in actual data

In [43]:
#FILTERING DATA (based on condition)
df[df["aqi"] < 50]
df[ (df["aqi"] < 50) & (df["temperature"] < 30)]

df[df["aqi"] < 50] [["city", "aqi"]]

              city  aqi
22        New York   49
43        New York   49
252       New York   43
533    Los Angeles   27
807         London   35
...            ...  ...
17624     Helsinki   43
17713       Zurich   48
17811       Zurich   45
17962       Zurich   47
17986       Zurich   38

[158 rows x 2 columns]

In [51]:
#FILTERING DATA THROUGH QUERY
aqi_val = 50
df.query("aqi < @aqi_val & temperature > 30") [["city", "aqi"]]
aqi_data = df.query("aqi < 50 & temperature > 30") [["city", "aqi"]].copy
aqi_data

<bound method NDFrame.copy of                city  aqi
22         New York   49
43         New York   49
960          London   16
1396          Paris   46
1430          Paris   45
1677         Berlin   35
1690         Berlin   49
2729        Toronto   44
3159    Mexico City   40
3330      São Paulo   45
3417      São Paulo   41
3510      São Paulo   45
3650   Buenos Aires   44
4012      Cape Town   35
6111         Riyadh   48
6395           Doha   45
6799         Mumbai   44
7023          Delhi   48
7258      Bengaluru   46
8035        Chennai   43
9008          Seoul   43
9163          Seoul   45
9519        Beijing   42
11600       Jakarta   49
11763       Jakarta   48
12029        Sydney   49
12532     Melbourne   47
13733        Tehran   35
13798        Tehran   49
15505       Chicago   43
16169       Houston   39
16880        Warsaw   35
16957     Stockholm   48
17624      Helsinki   43
17713        Zurich   48
17962        Zurich   47>